language: common-lisp
install:
  - sudo apt-get install sbcl pgtap ircd-irc2
  - wget -q http://beta.quicklisp.org/quicklisp.lisp -O ~/quicklisp.lisp
  - mkdir -p ~/quicklisp/local-projects/
  - svn checkout svn://common-lisp.net/project/cl-irc/svn/trunk ~/quicklisp/local-projects/cl-irc
  - git clone git://github.com/jd/clack.git ~/quicklisp/local-projects/clack
before_script:
  - sudo -u postgres createuser -S -R -D -E -l kawoosh
  - sudo -u postgres createdb -E UTF8 -O kawoosh -hlocalhost kawoosh
  - psql -U kawoosh -hlocalhost -d kawoosh -f `pg_config --sharedir`/extension/pgtap--*.sql
  - sbcl --load tests/.update-deps.lisp
  - ln -s $TRAVIS_BUILD_DIR ~/quicklisp/local-projects/kawoosh
script:
  - "sbcl --eval '(load (merge-pathnames \"quicklisp/setup.lisp\" (user-homedir-pathname)))' --eval \"(require 'kawoosh)\" --eval '(kawoosh.dao:create-tables)' --quit"
  - pg_prove -v -hlocalhost -Ukawoosh tests/*.sql | tee /tmp/pgprove.log
  - "grep -q '^Result: PASS' /tmp/pgprove.log"
  - sbcl --dynamic-space-size 2500 --load run-tests.lisp
notifications:
  email:
    - julien@danjou.info
