(load (make-pathname :directory (pathname-directory (user-homedir-pathname)) :name "quicklisp" :type "lisp"))
(quicklisp-quickstart:install)
(ql:quickload 'cl-irc)
(ql:quickload 'cl-json)
(ql:quickload 'cl-test-more)
(ql:quickload 'clack)
(ql:quickload 'drakma)
(ql:quickload 'fiveam)
(ql:quickload 'postmodern)
(quit)
